// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CS_Jelly
{
    internal sealed partial class Vsix
    {
        public const string Id = "CS_Jelly.e8fdc5d5-d35d-49ae-9f01-a7352d5819d6";
        public const string Name = "JellyUI";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Brock Claussen";
        public const string Tags = "";
    }
}
